$("#big").css({"width" : "650px", "height" : "600px","background-color" : "silver",})
setInterval(function f(){
    var min = document.createElement("div")
        $(min).css("position" , "absolute")
        var color = Math.floor(Math.random() * 240)
        var color1 = Math.floor(Math.random() * 240)
        var color2 = Math.floor(Math.random() * 240)
        var width = Math.floor(Math.random() * 150)
        var height = Math.floor(Math.random() * 150)
        var bottom = Math.floor(Math.random() * 400)
        var right = Math.floor(Math.random() * 500)
        var left = Math.floor(Math.random() * 500)
        $(min).css("width" , width + "px")
        $(min).css("height" , height + "px")
        $(min).css("background-color" , "rgb("+color+" "+color1+" "+color2+")")
        $(min).css("margin-left" , right + "px")
        $(min).css("margin-right" ,left + "px")
        $(min).css("margin-top" ,bottom + "px")
        $("#big").append(min)
    
},900)